site_name: DQ Programming Language
site_description: Documentation for the DQ programming language
repo_url: https://github.com/nvitya/dq-lang

theme:
  name: material
  features:
    - navigation.sections
    - navigation.indexes
    - content.code.copy
    - search.highlight

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Motivation: motivation.md
  - Getting Started: getting-started.md
  - Examples: examples/index.md
  - Language:
      - Basics: language/basics.md
      - Types: language/types.md
      - Expressions: language/expressions.md
      - Statements: language/statements.md
      - Functions: language/functions.md
      - Objects: language/objects.md
      - Modules: language/modules.md
      - Memory and Pointers: language/memory-and-pointers.md
      - Attributes and Directives: language/attributes-and-directives.md
      - Inter-Operation: language/interop.md
  - RTL:
      - Overview: rtl/overview.md
      - anyvalue: rtl/anyvalue.md
      - String Methods: rtl/strings.md
      - Text Formatting: rtl/textfmt.md
  - Standard Modules:
      - file: stdmodules/file.md
      - strutils: stdmodules/strutils.md
      - json: stdmodules/json.md
      - nanonet: stdmodules/nanonet.md
  - Compiler:
      - Getting the DQ Compiler: compiler/getting-dq-comp.md
      - Using the DQ Compiler: compiler/using-dq-comp.md
      - DQM Format: compiler/dqm-format.md
